"""add client nickname, mailing address, active flag, couple fields

Revision ID: 0c0244c3f3eb
Revises: a6a070210f6b
Create Date: 2026-08-03 11:51:11.119725
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0c0244c3f3eb'
down_revision: Union[str, Sequence[str], None] = 'a6a070210f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mailing_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_couple', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('partner_first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('partner_last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('patient_is_partner', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('patient_is_partner')
        batch_op.drop_column('partner_last_name')
        batch_op.drop_column('partner_first_name')
        batch_op.drop_column('is_couple')
        batch_op.drop_column('is_active')
        batch_op.drop_column('mailing_address')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
