"""add auth_config table

Revision ID: 6ed2183ce4ca
Revises: ca57db4e22aa
Create Date: 2026-07-30 19:54:18.740631
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ed2183ce4ca'
down_revision: Union[str, Sequence[str], None] = 'ca57db4e22aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_config')
    # ### end Alembic commands ###
