"""drop telehealth_url from appointment

Revision ID: a6a070210f6b
Revises: d4f15a4f2ad8
Create Date: 2026-08-03 10:44:08.585187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6a070210f6b'
down_revision: Union[str, Sequence[str], None] = 'd4f15a4f2ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('telehealth_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telehealth_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
