"""add appointment per-session diagnosis and cpt modifiers

Revision ID: b794e8364b15
Revises: c1f04f8c9170
Create Date: 2026-08-03 21:51:06.751730
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b794e8364b15'
down_revision: Union[str, Sequence[str], None] = 'c1f04f8c9170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnosis_codes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('modifier_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('modifier_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('modifier_3', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('modifier_4', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('modifier_4')
        batch_op.drop_column('modifier_3')
        batch_op.drop_column('modifier_2')
        batch_op.drop_column('modifier_1')
        batch_op.drop_column('diagnosis_codes')

    # ### end Alembic commands ###
