"""add payment servicer fee and refund, appointment write-off, provider credit fee percent

Revision ID: c1f04f8c9170
Revises: 0c0244c3f3eb
Create Date: 2026-08-03 16:15:24.425240
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c1f04f8c9170'
down_revision: Union[str, Sequence[str], None] = '0c0244c3f3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('written_off', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servicer_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_refund', sa.Boolean(), nullable=True))

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_fee_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('credit_fee_percent')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('is_refund')
        batch_op.drop_column('servicer_fee')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('written_off')

    # ### end Alembic commands ###
