"""add reminder preferences and notification log

Revision ID: ca57db4e22aa
Revises: 6637b25ef7a9
Create Date: 2026-07-30 13:28:42.347006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca57db4e22aa'
down_revision: Union[str, Sequence[str], None] = '6637b25ef7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('lead_slot', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', 'channel', 'lead_slot', name='uq_notification_slot')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_channel', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_consent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_opted_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('email_opted_out')
        batch_op.drop_column('email_consent_at')
        batch_op.drop_column('reminder_channel')

    op.drop_table('notification_log')
    # ### end Alembic commands ###
