"""add email_baa_confirmed to provider

Revision ID: d4f15a4f2ad8
Revises: 65ef944098de
Create Date: 2026-07-31 06:51:57.476934
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4f15a4f2ad8'
down_revision: Union[str, Sequence[str], None] = '65ef944098de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_baa_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('email_baa_confirmed')

    # ### end Alembic commands ###
